name: iomdailyazkar
description: "A new Flutter project."
publish_to: 'none'

version: 2.3.2+5

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  shared_preferences: ^2.5.3
  http: ^1.4.0
  adhan: ^2.0.0+1
  timezone: ^0.9.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  share_plus: ^7.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1
  upgrader: ^12.5.0
  get: ^4.7.2
  flutter_markdown: ^0.7.0
  connectivity_plus: ^7.0.0

  # Firebase
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/


  fonts:
    - family: Ador-Noirrit
      fonts:
        - asset: assets/fonts/Ador-Noirrit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ador-Noirrit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ador-Noirrit-Light.ttf
          weight: 300

    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri/HindSiliguri-Bold.ttf
          weight: 700
        - asset: assets/fonts/HindSiliguri/HindSiliguri-Regular.ttf
          weight: 600
        - asset: assets/fonts/HindSiliguri/HindSiliguri-Light.ttf
          weight: 300

    - family: NotoSerifBengali
      fonts:
        - asset: assets/fonts/NotoSerifBengali/NotoSerifBengaliBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerifBengali/NotoSerifBengaliRegular.ttf
          weight: 600
        - asset: assets/fonts/NotoSerifBengali/NotoSerifBengaliLight.ttf
          weight: 300

      # Arabic Fonts

    - family: Amiri
      fonts:
        - asset: assets/fonts/arabic/Amiri/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/Amiri/Amiri-Regular.ttf
          weight: 400

    - family: IndoPak
      fonts:
        - asset: assets/fonts/arabic/IndoPak/IndoPak.ttf
          weight: 700
        - asset: assets/fonts/arabic/IndoPak/IndoPak.ttf
          weight: 400

    - family: Scheherazade_New
      fonts:
        - asset: assets/fonts/arabic/Scheherazade_New/ScheherazadeNew-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/Scheherazade_New/ScheherazadeNew-Regular.ttf
          weight: 400

    - family: Uthmanic
      fonts:
        - asset: assets/fonts/arabic/Uthmanic/Uthmanic.otf
          weight: 400
